# Generated by Django 4.2.5 on 2023-09-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0005_product_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="detail",
            field=models.TextField(blank=True, null=True),
        ),
    ]
