# Generated by Django 4.2.5 on 2023-09-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Produmt",
            new_name="Product",
        ),
    ]
